# Generated by Django 4.2.1 on 2023-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_text", models.CharField(max_length=100)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
